/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package movie.ticket.booking;

import javax.swing.JOptionPane;

/**
 *
 * @author Priya
 */
public class frame_4 extends javax.swing.JFrame {

    /**
     * Creates new form frame_4
     */
    public frame_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(146, 70, 119, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(146, 104, 119, 28);

        jLabel1.setFont(new java.awt.Font("SimHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 126, 23);

        jLabel2.setFont(new java.awt.Font("SimHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PHONE NO.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 111, 105, 21);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kung fu panda 3", "The man who knew infinity", "baaghi", "sarabjit", "Captain America : Civil War" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(256, 186, 106, 20);

        jButton1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButton1.setText("next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 270, 150, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "powai", "kharghar", "andheri", "vashi", " ", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(400, 186, 106, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/inv ip pics/pink flower.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String movie=jComboBox1.getSelectedItem().toString();
       String place=jComboBox2.getSelectedItem().toString();
       if(movie.equals("kung fu panda 3")  )
    {
        if(place.equals("kharghar") || place.equals("vashi"))
    {   dispose();
        frame_5 c=new frame_5();
                c.setVisible(true);
        
    }     
       
       else{
            JOptionPane.showMessageDialog(null,"sorry! not available...");
       }
    }
       
       
       if(movie.equals("the man who knew infinity")  )
    {
        if(place.equals("kharghar") || place.equals("andheri"))
    {   dispose();
        frame_5 c=new frame_5();
                c.setVisible(true);
        
    }     
       
       else{
            JOptionPane.showMessageDialog(null,"sorry! not available...");
       }
    }
        
       if(movie.equals("baaghi")  )
    {
        if(place.equals("andheri") || place.equals("vashi"))
    {   dispose();
        frame_5 c=new frame_5();
                c.setVisible(true);
        
    }     
       
       else{
            JOptionPane.showMessageDialog(null,"sorry! not available...");
       }
    }
       if(movie.equals("sarabjit")  )
    {
        if(place.equals("kharghar") || place.equals("vashi"))
    {   dispose();
        frame_5 c=new frame_5();
                c.setVisible(true);
        
    }     
       
       else{
            JOptionPane.showMessageDialog(null,"sorry! not available...");
       }
    }
       
        if(movie.equals("Captain America : Civil War")  )
    {
        if(place.equals("powai") || place.equals("vashi"))
    {   dispose();
        frame_5 c=new frame_5();
                c.setVisible(true);
        
    }     
       
       else{
            JOptionPane.showMessageDialog(null,"sorry! not available...");
       }
    }
       
       
       
        
        
        
        
        
        
        
        
        
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
