/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package movie.ticket.booking;
import java.sql.*; ;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Priya
 */
public class frame_2 extends javax.swing.JFrame {

    /**
     * Creates new form frame_2
     */
    public frame_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        p1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("SEARCH BY TYPE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 330, 185, 31);

        p1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOVIE", "THEATER", "ADDRESS", "TYPE"
            }
        ));
        jScrollPane1.setViewportView(p1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 80, 390, 120);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 330, 120, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TYPE\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tempus Sans ITC", 2, 14)); // NOI18N
        jRadioButton1.setText("hollywood");
        jPanel2.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tempus Sans ITC", 2, 14)); // NOI18N
        jRadioButton2.setText("bollywood");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(150, 230, 100, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/inv ip pics/wallpaper_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        DefaultTableModel m1=(DefaultTableModel)p1.getModel();
        
                String bollywood=jRadioButton2.getText();
                String hollywood=jRadioButton1.getText();
        
                
           
                        if(jRadioButton1.isSelected())
                        {
          
               
                        try{
                                    m1.setRowCount(0);
                                    Class.forName("com.mysql.jdbc.Driver");  
                                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/inv_ip","root","priya123");
                                    Statement st=conn.createStatement();
                                    String query="select * from movie where Type='hollywood'";
                                    ResultSet rs=st.executeQuery(query);
                                    while(rs.next()){
                                    String d1=rs.getString("movie");
                                    String d2=rs.getString("theater");
                                    String d3=rs.getString("address");
                                    String d4=rs.getString("type");
                                    m1.addRow(new Object[]{d1,d2,d3,d4});
                                                           }
                                    rs.close();
                                    st.close();
                                    conn.close();
                              }
                                    catch(Exception e){
                                                JOptionPane.showMessageDialog(null,"check");

                                                    }
                    }   
      
           
                    if(jRadioButton2.isSelected())
                     {
          
               
                        try{
                                     m1.setRowCount(0);

                                     Class.forName("com.mysql.jdbc.Driver");  
                                     Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/inv_ip","root","tiger");
                                     Statement st=conn.createStatement();
                                     String query="select * from movie where Type='bollywood'";
                                     ResultSet rs=st.executeQuery(query);
                                     while(rs.next()){
                                     String d1=rs.getString("movie");
                                     String d2=rs.getString("theater");
                                     String d3=rs.getString("address");
                                     String d4=rs.getString("type");
                                     m1.addRow(new Object[]{d1,d2,d3,d4});
                                             }
                                     rs.close();
                                     st.close();
                                     conn.close();
                           } 

                                     catch(Exception e){
                                                 JOptionPane.showMessageDialog(null,"check");

                                                            }   
                      }   
        
        
        
       
                 
        
         
         
           
   
                   
       
                   
                   
                   
                   

                   
                   
                   
                   
                   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          if(jRadioButton1.isSelected() || jRadioButton2.isSelected())
             {    
        dispose();
                frame_3 c=new frame_3();
                c.setVisible(true);
}

           else
                        { 
                             JOptionPane.showConfirmDialog(null, "Please Select hollywood or bollywood", "", JOptionPane.OK_CANCEL_OPTION);

                         }  
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable p1;
    // End of variables declaration//GEN-END:variables
}
