/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package movie.ticket.booking;
import java.sql.*; ;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Priya
 */
public class frame_3 extends javax.swing.JFrame {

    /**
     * Creates new form frame_3
     */
    public frame_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        p2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        p2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOVIE", "THEATER", "ADDRESS", "TYPE"
            }
        ));
        jScrollPane1.setViewportView(p2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 110, 452, 91);

        jButton1.setFont(new java.awt.Font("Walt Disney Script", 1, 24)); // NOI18N
        jButton1.setText("search by place");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 310, 260, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "powai", "kharghar", "andheri", "vashi", " ", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 240, 68, 20);

        jButton2.setFont(new java.awt.Font("Walt Disney Script", 1, 24)); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 250, 100, 30);

        jButton3.setFont(new java.awt.Font("Walt Disney Script", 1, 24)); // NOI18N
        jButton3.setText("book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 250, 120, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/inv ip pics/blue.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 610, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      DefaultTableModel m1=(DefaultTableModel)p2.getModel();
      String place=jComboBox1.getSelectedItem().toString();
        if(place=="vashi")
                  {
                    try{
                        m1.setRowCount(0);
                        Class.forName("com.mysql.jdbc.Driver");  
                        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/inv_ip","root","priya123");
                        Statement st=conn.createStatement();
                        String query="select * from movie where Address='vashi'";
                        ResultSet rs=st.executeQuery(query);
                        while(rs.next()){
                        String d1=rs.getString("movie");
                        String d2=rs.getString("theater");
                        String d3=rs.getString("address");
                        String d4=rs.getString("type");
                        m1.addRow(new Object[]{d1,d2,d3,d4});
                                }
                        rs.close();
                        st.close();
                        conn.close();
              } 
         
                        catch(Exception e){
                        
                                    JOptionPane.showMessageDialog(null,"check");

                                               }   
                  }
                     if(place=="powai")
        {
                    try{
                        m1.setRowCount(0);
                        Class.forName("com.mysql.jdbc.Driver");  
                        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/inv_ip","root","tiger");
                        Statement st=conn.createStatement();
                        String query="select * from movie where Address='powai'";
                        ResultSet rs=st.executeQuery(query);
                        while(rs.next()){
                        String d1=rs.getString("movie");
                        String d2=rs.getString("theater");
                        String d3=rs.getString("address");
                        String d4=rs.getString("type");
                        m1.addRow(new Object[]{d1,d2,d3,d4});
                                }
                        rs.close();
                        st.close();
                        conn.close();
              } 
         
                        catch(Exception e){
                                    JOptionPane.showMessageDialog(null,"check");

                                               }   
                            }
                    if(place=="kharghar")
        {
                    try{
                        m1.setRowCount(0);
                        Class.forName("com.mysql.jdbc.Driver");  
                        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/inv_ip","root","tiger");
                        Statement st=conn.createStatement();
                        String query="select * from movie where Address='kharghar'";
                        ResultSet rs=st.executeQuery(query);
                        while(rs.next()){
                        String d1=rs.getString("movie");
                        String d2=rs.getString("theater");
                        String d3=rs.getString("address");
                        String d4=rs.getString("type");
                        m1.addRow(new Object[]{d1,d2,d3,d4});
                                }
                        rs.close();
                        st.close();
                        conn.close();
              } 
         
                        catch(Exception e){
                                    JOptionPane.showMessageDialog(null,"check");

                                               }   
        }
                   if(place=="andheri")
        {
                    try{
                        m1.setRowCount(0);
                        Class.forName("com.mysql.jdbc.Driver");  
                        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/inv_ip","root","tiger");
                        Statement st=conn.createStatement();
                        String query="select * from movie where Address='andheri'";
                        ResultSet rs=st.executeQuery(query);
                        while(rs.next()){
                        String d1=rs.getString("movie");
                        String d2=rs.getString("theater");
                        String d3=rs.getString("address");
                        String d4=rs.getString("type");
                        m1.addRow(new Object[]{d1,d2,d3,d4});
                                }
                        rs.close();
                        st.close();
                        conn.close();
              } 
         
                        catch(Exception e){
                                    JOptionPane.showMessageDialog(null,"check");

                                               }   
        }
        
                      
                                        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
         frame_2 c=new frame_2();
                c.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
         frame_4 c=new frame_4();
                c.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable p2;
    // End of variables declaration//GEN-END:variables
}
